/* this patches some of the binaries generated by vmasm
 * AKA manually corrupting them
 * to test the exceptions caused on corrupted binaries, as the assembler does not allow 
 * the generation with unknown instructions or some illegal states */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

int main(void) {

    const char *filename = "exceptions/unknown_instruction.bin";

    FILE *file = fopen(filename, "r+b");

    /* 0x18 = 24 */
    fseek(file, 24, SEEK_SET);

    int32_t patch[] =  {0xFFFFFFFF, 0xFFFF, 0xFFFF, 0xFFFF};

    fwrite(patch, sizeof(int32_t), 1, file);

    printf("exceptions/unknown_instruction.bin manually corrupted\n");

    fclose(file);

    return 0;
}
